### ISSUE TITLE
Add NSCoding Support

### ISSUE THREAD

**Issue by jeffd** [davecom/SwiftGraph#12]
By having a pure Swift implementation of a Graph, there's currently no way, as far as I can tell, to write a Graph to disk with NSKeyedArchiving / NSCoding.

**Comment by davecom** [comment]
That is correct. One could subclass `Graph`, `UnweightedGraph`, or `WeightedGraph` and specify `NSCoding` compliant vertices and add NSCoding conformance. Having such a class built-in to the framework would violate the framework's non-reliance on Foundation. I am interesting in exploring other serialization options including basic CSV text files for Graphs with String vertices, XML, and JSON.

**Comment by davecom** [comment]
The path forward on this will be conformance with the Swift 4 [archival and serialization APIs](https://github.com/apple/swift-evolution/blob/master/proposals/0166-swift-archival-serialization.md).
