### ISSUE TITLE
Index out of bounds crash removing vertex

### ISSUE THREAD

**Issue by brandonroth** [davecom/SwiftGraph#18]
I'm getting an array index out of bounds crash when removing a vertex, the crash is in `Graph.swift` line `207` and `226`.  It seems strange that it could crash there so I modified the function a bit to collect some more data by checking the index and printing out out some more data.

The modified loop in the function looks like:

```
        for j in 0..<index {
            print("Removing Vertices")
            let beginningCount = edges[j].count
            var toRemove: [Int] = [Int]()
            for l in 0..<edges[j].count {
                if edges[j][l].v == index {
                    toRemove.append(l)
                    continue
                }
                if edges[j][l].v > index {
                    edges[j][l].v -= 1
                }
            }
            for f in toRemove {
                
                if f < edges[j].count {
                    edges[j].remove(at: f)
                }
                else {
                    print("Number Of edges: \(edges[j].count), starting count: \(beginningCount) , toRemove: \(f)")
                }
            }
        }
```

When I run it I get things in the console like:
```
Removing Vertices
Number Of edges: 91, starting count: 144 , toRemove: 91
Number Of edges: 91, starting count: 144 , toRemove: 92
Number Of edges: 91, starting count: 144 , toRemove: 93
Number Of edges: 91, starting count: 144 , toRemove: 94
Number Of edges: 91, starting count: 144 , toRemove: 95
Number Of edges: 91, starting count: 144 , toRemove: 96
Number Of edges: 91, starting count: 144 , toRemove: 97
Number Of edges: 91, starting count: 144 , toRemove: 98
Number Of edges: 91, starting count: 144 , toRemove: 99
Number Of edges: 91, starting count: 144 , toRemove: 100
Number Of edges: 91, starting count: 144 , toRemove: 101
Number Of edges: 91, starting count: 144 , toRemove: 102
```
It seems as if the array is being modified from the beginning of the loop when it has 144 elements and the array of vertices to be removed is being calculate, to the next step when the vertices are being removed, but I can't see where the modification is being made.

**Comment by davecom** [comment]
Can you send over the code - or equivalent sample - that is causing the crash? It's very hard to debug without it. Thanks.

**Comment by davecom** [comment]
@brandonroth Any code sample? Otherwise I'm going to close this issue.

**Comment by brandonroth** [comment]
It's pretty difficult to put together a code sample from the project that I can reproduce the bug in, it's pretty integrated into the project and pulling it out with real data that recreates it is tough.

Anyways I think we found what's going on.  The `toRemove` array contains the indices to edges to remove, but the code is assuming that removing the first index does not invalidate subsequent indices. I think the crash happens intermittently because it will only crash if a subsequent index happens to point to the last element in the edges array so that removing the proceeding one will shift the end index by one causing the array out of bound error.

The fix that works for us is to take into account the `count` of `toRemove` when adding new indexes to the array.  I'll submit a PR  with the proposed fix.

**Comment by davecom** [comment]
Great catch - thanks!
