### ISSUE TITLE
Function to find cycles

### ISSUE THREAD

**Issue by ZevEisenberg** [davecom/SwiftGraph#30]
It would be useful to have a method that finds all elementary cycles (where no vertex is repeated except for the start/end one) in a directed graph. Here's an example from Mathematica: https://mathematica.stackexchange.com/questions/9434/finding-elementary-cycles-of-directed-graphs

**Comment by davecom** [comment]
That sounds like a nice addition. The existing property `isDAG` will tell you if a directed graph is acyclic — don't know if that helps you for your current application.

**Comment by ZevEisenberg** [comment]
I'm constructing explicitly cyclic graphs (finding possible juggling patterns, so any path through the graph eventually has to end up back at the starting position). Basically, I've used your library to construct the graph depicted on [this page](http://juggle.wikia.com/wiki/State_notation), and now I want to find all the possible cycles. Then, I'll filter the found cycles by various criteria given by the user (for example, limiting to a min or max length, or including a min- or max-height throw.

**Comment by ZevEisenberg** [comment]
Oh, and it looks like this algorithm is where it's at, although I'm having a little trouble translating from 1973-academic-ese into Swift, and the Java implementations I've found are a slog to get through: http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.335.5999&rep=rep1&type=pdf

**Comment by davecom** [comment]
Hmm yeah my initial searching comes back to the same paper. That would be the ideal algorithm to implement it looks like, but I think for now, just to have something working, a modification can be made to `topologicalSort()` to return all cycles (in a new function, not `topologicalSort()`). The `guard` statement in `visit()` will be triggered every time a cycle occurs. In another version of the function, it could build up a list of cycles, I think, if we add a parent property to `TSNode`.

**Comment by ZevEisenberg** [comment]
By the way, this library is way cool. I'm excited to see it grow, especially with #21. I'd love to make my graph into a value type (`struct`) instead of a subclass.

**Comment by davecom** [comment]
Thanks, much appreciated. In the mini-version of the library that's included in [Classic Computer Science Problems in Swift](https://github.com/davecom/ClassicComputerScienceProblemsInSwift) `Graph` has already been refactored into a protocol, so I think it's definitely feasible. However, it will be a breaking change for existing users of the library, so it's debatable whether it's worth it. Also unfortunately there are still some protocol limitations that get in the way of it being truly elegant.

**Comment by davecom** [comment]
@ZevEisenberg When you have a chance, can you test the new `detectCycles()` function against your graph? Thanks!

**Comment by ZevEisenberg** [comment]
Yes! I’ve got a hack day tomorrow and I’m planning on doing just that. Exciting!

**Comment by ZevEisenberg** [comment]
@davecom hey, Dave. I checked out your branch, and this is pretty cool! I have two questions:

1. Do you know what the time/space complexity characteristics of this algorithm are? Do you know how it compares to, for example, Johnson's Algorithm?
1. Would it be possible to have a version that returns the edges, rather than the vertices? My struct that conforms to `Edge` represents a "throw" in my juggling simulator, and a throw needs to have a "height" (integer) associated with it. It's not a weight, exactly, in that it doesn't affect the cost of getting from one node to another, but for my app, it's critical that I get back the edges associated in the cycles. I may try a PR for this.

**Comment by davecom** [comment]
@ZevEisenberg 

1. I looked into all of the known algorithms, and the original papers behind them. I also looked at papers that compare all of them. The wisdom on the Internet is that Johnson's algorithm (1975) is the most efficient. One comparative paper actually found Tarjan's (1973) and another from 1976 who's authors names escapes me, outperforms it. Here is that comparative paper: http://epubs.siam.org/doi/10.1137/0205007

Then there was this strange conference proceeding/paper from 2006 that had the authors' claiming to have discovered a "new algorithm" for this problem that had some advantages over the older algorithms. It's the proceeding by Liu and Wang that I cite in the implementation in `Cycle.swift`. They provide a clear description, but no pseudocode, no proof, and no asymptotic approximation. However the paper is cited 78 times and if you read it, their algorithm obviously works (so it's strange nobody thought of it before...). Upon careful reading, the Liu/Wang algorithm is even less efficient than they present it. The table they show is comparing performance (in literal seconds) from the original papers running on 1970s computers to their algorithm running in 2006. So, it's not a very efficient algorithm (it still loses), but it's really easy to implement. As you can see, I implemented it in about half an hour. And — it lets you stop after you get to cycles of a certain length, which the other algorithms don't. So, for now I think it's good enough for the project unless someone runs into some performance issues.

Sorry for the long explanation — I just studied this pretty carefully.

2. Thank you for #33 !
