### ISSUE TITLE
Running BFS/DFS and returning the names associated with edges

### ISSUE THREAD

**Issue by Erice224** [davecom/SwiftGraph#83]
Hello, 
I have string vertices in a weighted undirected graph. I created edges doing AddEdge(from: "name1", to: "name2", weight: xx). When i run BFS/DFS and print the list of edges i get back, the u and v fields are ints. I assume this is the index of the vertices. Is there a way to get the string name associated with the vertex at this point? 
Thanks.

**Comment by davecom** [comment]
Hi Eric,

You can call `vertexAtIndex()` to convert from an index to a vertex.

David

**Comment by Erice224** [comment]
Awesome Thank you! Really appreciate the work that went into this tool :D
