### ISSUE TITLE
Type `Graph<V>` does not conform to protocol `IndexableBase`

### ISSUE THREAD

**Issue by cansurmeli** [davecom/SwiftGraph#9]
Hello.

I was trying `SwiftGraph` with Swift 3 and I'm getting the following error:

`Type Graph<V> does not conform to protocol IndexableBase` for the below declaration inside Graph.swift:

`public class Graph<V: Equatable>: CustomStringConvertible, Swift.Sequence, Swift.Collection { ... }`

Any leads? Thanks.

**Comment by davecom** [comment]
Hi @cansurmeli ,
I haven't yet ported SwiftGraph to Swift 3 (the note in the Readme is a placeholder for the next version 1.1 which I hope to release soon based on the Xcode betas). I will reply to this issue when it's updated.
Thanks,
David

**Comment by davecom** [comment]
This should now be fixed with the latest commit.

**Comment by cansurmeli** [comment]
Thank you Dave 👍🏻
